### ISSUE TITLE
German versions

### ISSUE THREAD

**Issue by ei8fdb** [UKHomeOffice/posters#12]
I've created this issue as @gunbert has started on some German translations. This is great!

**Comment by guntbert** [comment]
@ei8fdb Thank you for the welcome!
Generally Draw is seen as the right tool for changing small parts of text in pdfs. From several discussions I understood that it doesn't change anything but the text. So it *should* be fine. But before putting more work into it I'd like to have them crosschecked.

As for my tools: 

- No access to OS X
- Everything that runs on linux is fine
- Windows programs are ok too

I don't want to generate a lot of work on your side and I know that with these posters layout is critical so providing the source in some word processor format might be suboptimal.

What comes to my mind right now is LaTeX - open, keeps layout, many tools are available ...

Maybe we could look at this from your side: Which formats that are better suited for being edited than *pdf* can you export?

**Comment by ei8fdb** [comment]
Hi @guntbert 

Thanks for letting me know about your tools and OS. This is helpful for us.

We've now created .SVGs of the files. If you do a merge you'll get the SVG files.

Can you try editing those and tell me how you're getting on? 

Bestem gruss.
Bis bald!

**Comment by guntbert** [comment]
Working with SVG directly is nice :-) 
I'm going to send a new PR, with only the svg-source.

**Question:** I noticed, that the y-coordinates of the texts for the left and right columns are not always the same - is this on purpose?
e.g. in low_vision.svg the code for the second row reads

    <g id="Dont-2" transform="translate(867.000000, 1063.000000)">
        <text id="bury-information" font-family="HelveticaNeue-Bold, Helvetica Neue" font-size="34" font-weight="bold" fill="#000000">
                    <tspan x="0" y="107">bury information</tspan>
                    <tspan x="0" y="147">in downloads</tspan>
        </text>
    ...   
    </g>
    <g id="Do-2" transform="translate(115.000000, 1084.000000)">
         <text id="publish-all-informat" font-family="HelveticaNeue-Bold, Helvetica Neue" font-size="34" font-weight="bold" fill="#000000">
                <tspan x="0" y="84">publish all information</tspan>
                <tspan x="0" y="124">on web pages</tspan>
          </text>
    ...
    </g>
`

**Comment by karypun** [comment]
@guntbert Sorry for the delay in getting back to you. The y-coordinates of the left and right columns may have been an oversight. Good spot!




@guntbert We needed the posters for an event today, thats why we created a complete translation. Maybe you could have a look on our version.
