### ISSUE TITLE
What is the best graphics file format to create for people?

### ISSUE THREAD

**Issue by ei8fdb** [UKHomeOffice/posters#13]
We've started to get requests from people who don't use OS X and the Sketch application (sketchapp.com). We knew this would happen at some point.

So we'd like to ask for your advice: 

1. What is the best file format to produce?
2. What graphics applications are you using?

Our objective is to enable people who want to translate the posters into any language, on any operating system, with any graphics application.

Some programmes I'm aware of are: GIMP (https://www.gimp.org/), Inkscape (www.inkscape.org/).

Any information or advice, would be really helpful.

**Comment by elioqoshi** [comment]
Definitely SVG. I use PDF sometimes for non tech savvy people to preview directly.

**Comment by hellocatfood** [comment]
SVG is the most portable. For that Inkscape, Illustrator, Scribus are good programs to use. Even GIMP and Photoshop can read them

**Comment by ei8fdb** [comment]
We've been getting lots of feedback. Thanks everyone here and on the Twitters. 👍 

**Summary**
It seems as if .SVG is the best file to start with. We'll see if Sketchapp will export to an SVG, and try editing it with Inkscape.


**More in depth info**
So far we have file formats:

- SVG (is probably the best) [1]
- editable PDF [1]
- SVG (can embed text. If user installs font, its editable Inkscape) [2]
- .svg for vector for raster images [3]
- maybe .ora (open raster) [3]
- maybe .kra (krita file) [3]
- or .xcf (gimp file) [3]
- SVG [4]
- SVG [5]

**Applications to support**
- Inkscape
- Gimp


[1] https://twitter.com/gavinelliott/status/793560156688744448
[2] https://twitter.com/elioqoshi/status/793559363055214592
[3] https://twitter.com/bkurdali/status/793559057084850176
[4] https://twitter.com/htmlandbacon/status/793558205158854656
[5] https://twitter.com/hbons/status/793556910159060993

**Comment by ejnaren** [comment]
Other editors to have in mind. Affinity and Gravit.

**Comment by prokoudine** [comment]
Both KRA and XCF are very much like PSD: a wee bit too app-specific. ORA doesn't support text currently.

For SVG, please read http://tavmjong.free.fr/blog/?p=938 (a blog post from 2013) and check if it's currently doable with SVG2 and CSS3.

**Comment by karypun** [comment]
@ei8fdb Sketch does export to SVG. I've added the svg files within the UK version. Opened them in Illustrator and they seem to be ok. If there's problems opening them in other software could you let us know? Thanks everyone.

**Comment by lanodan** [comment]
* SVG, but export non-standard glyph(i.e. icons).

And there is also issues with boxes… (probably because it’s not “well-done” SVG).
Here is a what rsvg-convert(librsvg) gives me with autistic spectrum (firefox have the same bugs).
![autistic-spectrum](https://cloud.githubusercontent.com/assets/3816428/20025296/4fa3ad50-a2ed-11e6-9514-2010098ec24a.png)
Haven’t tested yet with inkscape.

**Comment by guntbert** [comment]
@lanodan you need to install the _FontAwesome_ (see http://blog.guntbert.net/2016/11/05/translating-httpsgithub-comukhomeofficeposters/ for my itinerary).

**Comment by guntbert** [comment]
My current take is to just change the text in the svg-files.

**Comment by athyuttamre** [comment]
[Figma](http://figma.com) is a new tool which allows design collaboration and is cross-platform by nature (built on the web.) It's free for students, but could be free for open source orgs too.

Full disclosure: I worked there as an intern in the past.

**Comment by sassquad** [comment]
I'm a bit late to the party, but I agree with SVG being the preferred format. It's been supported in browsers for a long time, and is therefore very mature as a vector format. There are very good articles from the likes of Sara Soueidian (sic?) who know the format very well, and how to keep them clean for use in web and print media.

**Comment by thblt** [comment]
I'm very late to the party too, but... has HTML+CSS been considered? It is probably the most widespread page layout format, would be more than sufficient for the simple design of these (very cool) posters and conversion to PDF can be a breeze with wkhtmltopdf (FOSS) or PrinceXML and even automated with a simple makefile or even a short script.  A minor drawback may be limited or nonexistent support for CMYK (I'm not sure, never tested) but perfect color accuracy is not relevant here.
