### ISSUE TITLE
deaf_fr.pdf > Spelling mistake

### ISSUE THREAD

**Issue by Johan-Ramon** [UKHomeOffice/posters#14]
Hello,

In "deaf_fr.pdf", in the sentence "laisser le choix aux utilisateur de choisir leur moyen de communication préféré", missing an "s" to "utilisateur".

Johan

**Comment by ei8fdb** [comment]
Thanks @Johan-Ramon for picking this up. 

@htmlzengarden has pushed a correction for this, so I'll close this issue now.

Thanks a lot for your help.
