### ISSUE TITLE
Traditional Chinese version

### ISSUE THREAD

**Issue by Vi-Naita** [UKHomeOffice/posters#19]
https://drive.google.com/drive/folders/0B4oaXOSq8RsFcEJBTDFKaUJmVUU

I don't know how to create new pull request

**Comment by karypun** [comment]
Hey @Vi-Naita we'll help you do this. Sorry for the delay :)

**Comment by Vi-Naita** [comment]
Hi @karypun , thanks a lot. I'm try to figure out.

**Comment by Vi-Naita** [comment]
Hi @karypun , I think I get it.

[posters_tw](https://github.com/Vi-Naita/posters/tree/master/accessibility/posters_tw) 😄

Is that right?

**Comment by karypun** [comment]
@Vi-Naita Yes, we're almost there :) What is the difference with the posters in the expand folder and the others?

**Comment by Vi-Naita** [comment]
Hi @karypun , I afraid that font error destroy layout appearance. So I prepared expand type, the letter in this post has turn into picture.
Am I think too much? 😕

**Comment by karypun** [comment]
@Vi-Naita Understood. No worries. I'll help you with the pull request now.
