### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by marcusferbrache** [UKHomeOffice/posters#2]
Hi

Can you confirm what the copyright situation is for the posters? Are they for anyone to reproduce?

Thanks in advance!

Marcus

**Comment by ei8fdb** [comment]
Hi Marcus!

Thanks for the query. I am looking for an answer on the question of copyright and licensing right now.

In the mean time, our hope is that the posters be used far and wide to promote access needs work in services.

I'll try and answer your query in the next few days.

**Comment by ei8fdb** [comment]
Hi @marcusferbrache 

Sorry for the delay in getting back to you. We've now got the licensing information attached to the posters - we've licensed them Creative Commons BY NC SA.

So, fork the repo, translate them and use them! We'd really appreciate it if you could then send a PR so we can merge the translated posters to our repo. 

It'd be a great if we could show our bosses how wide they've travelled! :)

Any questions, let us know.

**Comment by jdittrich** [comment]
Hi @ei8fdb, I am really happy to see this being licensed as CC. However, I find Non-Commercial licenses can be really difficult in practice. 

I know, that it is often easier to "sell" CC with the NC to a boss, so I understand if it was hard enough already. However, if you think it is possible to reconsider, I recommend
https://commons.wikimedia.org/wiki/File:Free_Knowledge_thanks_to_Creative_Commons_Licenses.pdf for a structured overview of the NC problems in relation to typical goals of organization like yours.
