### ISSUE TITLE
Using an open typeface for body copy

### ISSUE THREAD

**Issue by indrora** [UKHomeOffice/posters#23]
It's hard to reproduce this without running OSX or bending over and getting a license from the folks at Linotype. As much as I like Helvetica Neue, I'm not at the liberty to either a) pirate it or b) drop $350+ for a few OTFs.

Possibly the nicely similar [Source Sans Pro](http://adobe-fonts.github.io/source-sans-pro/)?

**Comment by karypun** [comment]
@indrora Happy for you to use that.
