### ISSUE TITLE
Giving credit on Twitter for poster translations

### ISSUE THREAD

**Issue by karypun** [UKHomeOffice/posters#25]
Hello @mhtpn @ilianM @Vi-Naita 

Thank you so much for your help on translating the posters.
We'd like to share them on Twitter and give credit to you. Are you on Twitter and if so what is your twitter handle?

Many thanks.

**Comment by Vi-Naita** [comment]
My [Twitter](https://twitter.com/ViBegonia), but I use Facebook more 😆

**Comment by mhtpn** [comment]
Hi, our twitter handle is @accessibilitynl

Kind regards,

Martijn

Op ma 14 nov. 2016 om 12:11 schreef karypun <notifications@github.com>
