### ISSUE TITLE
repo needs README with direct viewable links

### ISSUE THREAD

**Issue by tantek** [UKHomeOffice/posters#32]
This looks like an amazing repo.

It would be great if it had a README at the top level that linked to viewable versions of the posters, just to make them one-click accessible directly from the repo home page.

Thanks for your consideration!

**Comment by joelanman** [comment]
I made this - it might be helpful:

http://www.git-browser.com/ukhomeoffice/posters

**Comment by tantek** [comment]
Didn't see any direct links to viewable posters on that page. Am I missing something?

**Comment by joelanman** [comment]
If you browse around you can see thumbnails of the posters eg

http://www.git-browser.com/ukhomeoffice/posters/accessibility/posters_en-UK

It's not the same as all of them in one place but I thought it might be helpful

**Comment by karypun** [comment]
Hi, am closing this as this is done. Thanks.
