### ISSUE TITLE
Consider using freely available fonts

### ISSUE THREAD

**Issue by saparvia** [UKHomeOffice/posters#37]
The font used in the original posters seems to be Neue Helvetica, which is only available commercially. It would be easier to create visually consistent translations if a freely available font was used instead. Perhaps DejaVu Sans.

**Comment by pkoutsod** [comment]
I totally agree with saparvia. It was the first thing that came on my mind when I opened a pdf and tried to translate it.

**Comment by pkoutsod** [comment]
@saparvia, I think that the closed issue #23 answers this issue. Personally, I will use the 'source-sans-pro' font as suggested. :-)

**Comment by ei8fdb** [comment]
Hi @saparvia and @pkoutsod,

Thanks for finding that issue about Source Sans Pro. I forgot to update the README with the font information. I've done that now.

If you have any other questions, please let us know! Thanks again to you both.

**Comment by ei8fdb** [comment]
I'm going to close this now, but if there are any more questions, let us know.
