### ISSUE TITLE
French version

### ISSUE THREAD

**Issue by chrishrmnn** [UKHomeOffice/posters#4]
Hi dear friends from UK,
with [@mviry](https://twitter.com/mviry), we are interested about translating these poster in French. It is possible?
Off course, I'll commit french version in this repository. Just told me if I have to create another branch or just another file with "_FR" at the end.

Merci!

**Comment by ei8fdb** [comment]
Bonjour @chrishrmnn!

Yes, it is definitely possible to translate them into French. That would be excellent.

Would it help if we uploaded the sketch files for you? We'll see if that's possible.

About the commit: if you fork the repo, translate them, and send a PR we can then merge them.

Also, yes, add _fr to the end.

We are just waiting for confirmation about the licensing (see issue #2) and we'll up date here and #2.

One request: if you use them, we'd love to see some photos of them being used, and also some idea of where - is this in the French government, or somewhere else?

Thanks for getting in touch!

**Comment by chrishrmnn** [comment]
Thank you @ei8fdb for you quick and positive answer!
I can edit the PDF files directly in Illustrator if you can't share the Sketch files.

I am just waiting your confirmation about licensing and we'll start translating.

We want to translate these posters for the french Web community because french people are not so friendly with english! ;-) 
I'll probably print them for work too, if I do I'll post some photos.

**Comment by ei8fdb** [comment]
@chrishrmnn 

Actually I think [this](https://github.com/UKHomeOffice/posters/blob/master/accessibility/dos-donts-accessibility.sketch) raw file is the sketch file with all the posters. 

Just let me know if you can open the it - and if its the right file.

Yes, of course, I totally understand why you want to translate them. Better in lots of languages.

Looking forward to getting the PR! :)

**Comment by mhtpn** [comment]
Hi, 

Thanks for these awesome posters!
I have the same question as @chrishrmnn , would it be OK if I translated this to Dutch? I'll fork and send a PR with an _nl extension. 

Kind regards

**Comment by karypun** [comment]
@mhtpn sure! Just make sure that you keep the credits that are on the bottom of the posters. 
Many thanks

**Comment by ei8fdb** [comment]
Hi @chrishrmnn @mhtpn @mviry

We've updated our README with the licensing and translation information (thinking about it we should put it into a seperate TRANSLATION and LICENSE.MD, right?).

As I mentioned here in #2 we've licensed the posters as Creative Commons NC BY SA.

Could you help us help you: which other file format would be useful to people? 

If you're interested in translating them, please do. Just:

- clone the repository
- translate them
- add 2 or 3 letter language code to the end of ech poster - e.g. "screenreader_fr.pdf."
- send a pull request so we can merge them, or tell us where they are so we can advertise them here

Also, it'd be great if we could get some photos of them in action!

Any questions, let us know!

**Comment by Vi-Naita** [comment]
Traditional Chinese version (*_tw) :
https://drive.google.com/drive/folders/0B4oaXOSq8RsFcEJBTDFKaUJmVUU?usp=sharing

Almost there!

**Comment by ei8fdb** [comment]
Hi @Vi-Naita 

That's excellent. Thanks very much. Let us know when you're finished and we'll give you full credit for the translation.

Thanks!

**Comment by Vi-Naita** [comment]
@ei8fdb , they're finished :D

Traditional Chinese version (*_tw) :
https://drive.google.com/drive/folders/0B4oaXOSq8RsFcEJBTDFKaUJmVUU

**Comment by ei8fdb** [comment]
@chrishrmnn just to update you, @htmlzengarden and @juliemoynat have pushed some French localistions, in PR #10.

If you're interested, it'd be great if you were able to have a look and we can have a discussion about localisation if needs be.

Thanks!

**Comment by ei8fdb** [comment]
Hi @mhtpn, I was wondering if you had any progress on the Dutch versions? I've created a seperate issue (#11)  for them. No pressure, just checking. ;)

If we can help, let us know!

**Comment by Johan-Ramon** [comment]
Hello,

In "deaf_fr.pdf", in the sentence "laisser le choix aux utilisateur de choisir leur moyen de communication préféré",  missing an "s" to "utilisateur".

Johan

**Comment by mhtpn** [comment]
Hi @ei8fdb , we are working on it, trying to make a fitting translation that matches the design of the posters. Dutch is quite a wordy language, so that makes it challenging sometimes.

**Comment by ei8fdb** [comment]
@mhtpn Great, thanks for letting me know. And yes I understand about the difference in languages.

If we can help let us know. We're interested to see how you're approaching this.

One request: could we switch the discussion about the Dutch posters to this issue #11 - Dutch versions?

Thanks!
