### ISSUE TITLE
Typo in german version

### ISSUE THREAD

**Issue by ztiromoritz** [UKHomeOffice/posters#42]
There is a typo in one of the german pdfs:
  posters/accessibility/posters_de/screenreader_de.pdf
First headline: "Benuzer" has to be "Benutzer".

(I would fix it myself:
Is the sketch-file the master document?
Which software do you use to edit it?)

**Comment by karypun** [comment]
@ztiromoritz yes, the sketch file is the master document. You could fix it but feel free to have a chat with @ilianM who initially created the German version if you'd like to collaborate on any further changes.

**Comment by spoobar** [comment]
accessibility/posters_de/low-vision_de.pdf

"Bedeutung nur mit Farben vermitteln" (not "verbvermitteln")

**Comment by karypun** [comment]
@ztiromoritz @spoobar updates to both screenreader and low vision posters done. Thanks for your help!
