### ISSUE TITLE
Typo in accessibility-posters-next trial.pdf

### ISSUE THREAD

**Issue by johnpgreen** [UKHomeOffice/posters#44]
Final row, left column has "cosistent" instead of "consistent".

**Comment by karypun** [comment]
@megandrodger are you able to change this?

**Comment by karypun** [comment]
Thanks @megandrodger for fixing it.
@johnpgreen it's now updated. We got rid of the accessibility-posters-next trial.pdf as that was for initial testing with screen readers.
