### ISSUE TITLE
pt-br poster for dyslexia has no content

### ISSUE THREAD

**Issue by Bledson** [UKHomeOffice/posters#49]

**Comment by karypun** [comment]
@Bledson - appreciate you raising the issue. @msales78 are you able to fix this? Thank you.

**Comment by amchap** [comment]
@Bledson if you download the file, the content is there

**Comment by msales78** [comment]
@karypun I will correct and send again, but if you download, the content is ok.

**Comment by karypun** [comment]
Thank you @msales78
