### ISSUE TITLE
Glyph missing

### ISSUE THREAD

**Issue by VioletVivirand** [UKHomeOffice/posters#5]
Hi guys! This is an amateur translator from Taiwan. I'm working on translating the posters into Traditional Chinese (which is official language of Taiwan and Hong-Kong). But when I opened the file, some glyph was missing and made the document look weird.

Here is a screenshot from the document generated from you:

![2016-10-21 3 40 04](https://cloud.githubusercontent.com/assets/2352887/19590526/04afa784-97a5-11e6-8e5f-c7813b316530.png)

And this is mine:

![2016-10-21 3 41 21](https://cloud.githubusercontent.com/assets/2352887/19590628/748ceb20-97a5-11e6-9fb1-72673d367fc9.png)

Is there any method to fix it?

Oh, another question: I think we don't have the right to use GDSTransportWebsite font family, so I choose [Noto Sans CJK TC](https://www.google.com/get/noto/) made by Google Inc. Is it okay with you?

Thank you! Have a good day 😃

**Comment by karypun** [comment]
Hi @VioletVivirand,
Sorry about that. The glyph issue has to do with not having the icon font Font Awesome which you can download from their site: http://fontawesome.io/.

Alternatively, I'll look into revising the file so you don't need to download the font if you don't have it. With regards to Noto Sans CJK TC, that is fine to use. In the file, I'm going to removing the GDS font where applicable (it's only on the buttons).
