### ISSUE TITLE
Dyslexia contains do in the don't section

### ISSUE THREAD

**Issue by riconeitzel** [UKHomeOffice/posters#50]
The dyslexia poster contains behaviour guidelines in the right "false" column while it should NOT contain these; rather have them in the left "right" column!

that applies at least to the current -de version
https://github.com/UKHomeOffice/posters/blob/master/accessibility/posters_de/dyslexia_de.pdf

**Comment by karypun** [comment]
@ilianM are you able to speak to @riconeitzel about this issue? thanks.

**Comment by riconeitzel** [comment]
@ilianM @karypun I could help with german and english and could create a pullrequest … unfortunately all posters are in the same sketch file and it will - for sure - result in a merge conflict …

So … if you say: go ahead … I'll do the PR for en/de asap.

**Comment by karypun** [comment]
@riconeitzel that would be great, let's give it a try. thanks.

**Comment by riconeitzel** [comment]
#done :-)
