### ISSUE TITLE
Image for figurative phrases

### ISSUE THREAD

**Issue by KeithRhodes** [UKHomeOffice/posters#55]
The posters for autistic-spectrum_xx and deaf_xx (where xx is a language code, such as fr or tw) contain an image representing the idiomatic expression for "it is raining heavily", based on the British expression "it is raining cats and dogs".

This has been:
- incorrectly left as cats and dogs in de,
- correctly replaced by an image representing the expression "está lloviendo a cántaros" in es,
- correctly replaced by an image representing the expression "il pleut des cordes" in fr,
- incorrectly left as cats and dogs in nl,
- incorrectly left as cats and dogs in pt-BR,
- incorrectly left as cats and dogs in pt-PT,
- incorrectly left as cats and dogs in tr,
- possibly correctly replaced by a basin in tw,
- incorrectly left as cats and dogs in zh-TW,

Suggested expressions, taken from https://www.omniglot.com/language/idioms/rain.php are:
- image representing the expression "Es regnet Bindfäden - It's raining twine" in de,
- image representing the expression "Het regent pijpestelen - It's raining pipe stems" in nl,
- image representing the expression "Está chovendo a cântaros" in pt-BR,
- image representing the expression "Está chovendo a cântaros - It's raining jug[ful]s" in pt-PT,
- image representing the expression "Sicim gibi yağmur yağıyor - It's raining like long strings of rope" in tr,
- use the same in zh-TW as in tw.

Note that the image for de and tr can be the same as in fr; and that for pt-BR and pt-PT can be the same as in es.

**Comment by karypun** [comment]
thanks @KeithRhodes for looking into this. Am copying in @ilianM @mhtpn @msales78 @pedrocs @VioletVivirand @lahmacun for their consideration and thoughts

**Comment by pedrocs** [comment]
I agree, images should be adjusted accordingly. European Portuguese uses "Chove a potes", since "potes" is a more common word in Portugal for "cântaros", both meaning "jugs" or "pots".

How should we go about remaking these illustrations?

**Comment by karypun** [comment]
@pedrocs if you look at the Spanish poster for autism, there's a picture of jugs of water being poured down. Would you be able to use that?

**Comment by pedrocs** [comment]
Ah, I hadn't realised! OK, it's done, I'll do the pull request.

**Comment by Ryuno-Ki** [comment]
There are [several ways](http://www.dict.cc/englisch-deutsch/It's+raining+cats+and+dogs.html) to translate „It is raining cats and dogs” into German.

Two coll. are „Es gießt wie aus Kübeln” (literally „It pours like out of buckets”) and „Es regnet Bindfäden” (literally „It is raining pack-twine”).

**Comment by lahmacun** [comment]
@karypun The image in the Spanish poster can be used in Turkish posters as well. In Turkish "Bardaktan bosalir gibi yagmur yagiyor" means "It's raining like the water is falling down from cup". My Sketch license has ended. I'm glad If somebody can edit Turkish poster's image.

**Comment by karypun** [comment]
@lahmacun It's updated now
