### ISSUE TITLE
'Don't rely on accurate spelling, don't provide autocorrect'

### ISSUE THREAD

**Issue by nickcolley** [UKHomeOffice/posters#65]
Should this be  'Don't rely on accurate spelling, do provide autocorrect' ?

http://ukhomeoffice.github.io/posters/accessibility/html-posters/dyslexia1.html

**Comment by megandrodger** [comment]
Thanks for pointing this out Nick! Has been edited.


Megan Rodger

Interaction Designer


Digital, Data and Technology

Home Office

07912613016


________________________________

**Comment by nickcolley** [comment]
Closing this out, thanks a lot :)
