### ISSUE TITLE
Deafness Poster: Repetition of word "don't"

### ISSUE THREAD

**Issue by kevinliuzzo** [UKHomeOffice/posters#7]
On the poster for users who are Deaf or hard of hearing, the bottom item in the "Don't" column reads "Don't make telephone the only means of contact for users."

The word "don't" is redundant in this context as it is implied at the top of the column.
![screenshot 2016-10-28 15 04 36](https://cloud.githubusercontent.com/assets/165197/19818891/e7d0921a-9d1f-11e6-89e8-e3dd0aff9887.png)

Note: I printed these out for our company and our copy editor with 30+ years of experience noticed this within 10 seconds of me hanging them up and made me post this correction.

**Comment by kyleabailey** [comment]
Fair play to your copy editor.

**Comment by karypun** [comment]
@kevinliuzzo we've now made the correction. Thanks!
