### ISSUE TITLE
[info] A List Apart: Mental Illness in the Web Industry

### ISSUE THREAD

**Issue by Ryuno-Ki** [UKHomeOffice/posters#77]
Hi,

I want to draw your attention to [Mental Illness in the Web Industry](http://alistapart.com/article/mental-illness-in-the-web-industry) by [Brandon Gregory](http://alistapart.com/author/brandongregory) which was published yesterday and could help understanding part of the target audience of this repository better.

So this is just an info. I am fine if the issue gets closed immediately (after reading) :-)

**Comment by karypun** [comment]
Thanks @Ryuno-Ki I'll let our team know about this :)
