### ISSUE TITLE
Explanation of "Designing for users who are deaf" guidelines?

### ISSUE THREAD

**Issue by djrobstep** [UKHomeOffice/posters#84]
Hi there,

First, thanks for producing these posters. They are really good, and I intend to use them at my workplace. 

Just wondering about the rationale behind some of the guidelines tho, in particular the "Designing for users who are deaf or hard of hearing" poster.

It's unclear how some of them apply to these users more than the general population. Specifically: 

- write in plain language
- use a linear, logical layout
- break up content with subheadings, images and videos

I've googled around but can't find any rationale of these on gov.uk sites or elsewhere.

Obviously these are all good guidelines generally speaking, but their relevance to this group of people specifically is not obvious, at least to me.

Perhaps there could be some explanatory text or links included on each poster or at least with the repository?

**Comment by jbuller** [comment]
Thanks for the interest and query. We'd love to see a picture of the posters in your workplace and hear what impact they have had.

Most of the guidance on that poster relates to people for who use sign language is their first language. These people may never have heard or fully spoken another language. 
British Sign Language for example has important spatial aspects and different grammar structure and vocabulary to English. This means many BSL users report difficulty reading English. Therefore it is especially important to write well structured clear text, to aid comprehension and minimise the amount of reading required. It also helps to provide (supporting cues to) the information as graphics (diagrams, charts, illustrations) and video. Ideally the same information as would also be available in full as BSL either pre-recorded video or perhaps live on-screen interpretation.

We are looking at how we could provide more background information to the posters.

Thanks again.

**Comment by djrobstep** [comment]
Thanks for the info @jbuller and @Ryuno-Ki . Very informative!

@jbuller I will post some pictures of the posters here soon. Thanks again for you and your team's efforts on this.
