### ISSUE TITLE
http://www.git-browser.com/ukhomeoffice/posters/accessibility/posters_en-UK link is broken

### ISSUE THREAD

**Issue by accessiblewebuk** [UKHomeOffice/posters#85]
The page just shows "Cannot read property 'children' of undefined"

**Comment by zuzak** [comment]
Is http://www.git-browser.com/ukhomeoffice/posters/accessibility what you're looking for?

It looks like they've got renamed.

**Comment by accessiblewebuk** [comment]
Thanks @zuzak - the broken link is on https://github.com/UKHomeOffice/posters where is says "view all the posters before you start working on them."

**Comment by zuzak** [comment]
Thanks for pointing it out; I've fixed the issue in #86 and it'll get merged once someone else gives the OK.

**Comment by joelanman** [comment]
Thanks for raising - it's worth me making missing pages better on Git Browser too :)
