### ISSUE TITLE
Privacy Series

### ISSUE THREAD

**Issue by mgifford** [UKHomeOffice/posters#90]
Would love to see what your team comes up with for educating people about the GDPR.  I do think it would be a great series. Some interesting ideas here https://ico.org.uk/for-organisations/resources-and-support/posters-stickers-and-e-learning/

**Comment by owenm6** [comment]
Hi Mike. We are currently focusing on improving our current set of guidance, so are not looking to expand our poster set at this time. But thank you for the suggestion.
