### ISSUE TITLE
Adapting dutch posters to our organisations style

### ISSUE THREAD

**Issue by lizasiegerist** [UKHomeOffice/posters#96]
Hi, 

We would like to use the Dutch posters within our organization to create some attention for accessibility. If possible we would like to adapt the poster a little so they fit our corporate identity. Are there any other formats of the posters available besides the pdf files?

Regards,

Liza

**Comment by owenm6** [comment]
Hi Liza,

We have [template versions](https://github.com/UKHomeOffice/posters/tree/master/accessibility/dos-donts/posters_en-UK) of the posters for use with [Sketch](https://www.sketchapp.com/) and SVG versions of each poster which should be compatible with a variety of graphics software. Unfortunately the templates are in English.

https://github.com/UKHomeOffice/posters/tree/master/accessibility/dos-donts/posters_en-UK
 
Thanks,
Michael

**Comment by lizasiegerist** [comment]
Thanks Michael! I think this can help!
